---
- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        secrets:
          SENDGRID_API_KEY: "{{ lookup('aws_ssm', '/email-verifier/sendgrid-api-key') | to_json }}"
          GMAIL_REFRESH_TOKEN: "{{ lookup('aws_ssm', '/email-verifier/gmail/refresh-token') | to_json }}"
          GMAIL_CREDENTIALS: "{{ lookup('aws_ssm', '/email-verifier/gmail/credentials') | to_json }}"
